### PR TITLE
test: added (commented out) groupby tests

### LINKED ISSUE #22: add group by table tests
(in exec_test)

### PR DESCRIPTION
**Pull request by osterbit**
closes #22

### CODE REVIEW

**Comment by osterbit** [comment]
@b5 should I comment out the other test that is failing and make an issue for now?

**Comment by b5** [comment]
ugh, nah this looks like a test you didn't write, correct? If so it's because our sql tests are currently flaky (because our codebase is a touch on the flaky side). I often have run tests more than once to get them to pass, and I've set aside a holiday project for myself to figure out the source of the problem.

**Comment by b5** [comment]
If re-running the build generates a pass we're good to merge, but lemmie review first

**Review by b5 — APPROVED** [review]
🇲🇴 Ⓜ️ 🥋

**Comment by osterbit** [comment]
added #25 to deal with later

**Pull request merged**
